### ISSUE TITLE
Allow `git` gem to get 2.0 and newer

### ISSUE THREAD

**Issue by zmariscal** [nevinera/quiet_quality#129]
I work on a Ruby on Rails project and we'd like to update the `git` gem. Looking at the [gemspec](https://github.com/nevinera/quiet_quality/blob/main/quiet_quality.gemspec#L34C3-L34C39) it appears we're not able to upgrade due to how the gemspec is currently setup.

**Comment by nevinera** [comment]
Resolved by #130
