### ISSUE TITLE
Support a `--light` and --quiet` logging mode for bin/qq

### ISSUE THREAD

**Issue by nevinera** [nevinera/quiet_quality#37]
Allow `qq` to be run with:

(a) a `--light/-l` flag that causes it _not_ to print out the individual tool outcomes and messages, but instead to print out an aggregate outcome on one line like "Ran 3 tools, 2 failed (standardrb, rspec)"

(b) a `--quiet/-q` flag that causes it to print out _nothing_ and only indicate failure/success via exit status.

**Comment by JonathanWThom** [comment]
I am working on this 🤚 . But if you don't see any movement in 2 weeks then you can assume I've abandoned it.
